import { jsPDF } from "jspdf";

import type { ReportItemData } from "@/types/report";

const PAGE_MARGIN = 15;
const FOOTER_Y_PADDING = 8;
const IMAGE_COLUMN_RATIO = 0.35;
const FEATURE_COLUMN_RATIO = 0.2;
const ROW_MIN_HEIGHT = 34;
const CELL_PADDING = 3;

type ImageData = {
  dataUrl: string;
  width: number;
  height: number;
  format: "PNG" | "JPEG";
};

const fileToDataUrl = (file: File): Promise<string> =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = () => reject(new Error("Failed to read image file."));
    reader.readAsDataURL(file);
  });

const getImageDimensions = (dataUrl: string): Promise<{ width: number; height: number }> =>
  new Promise((resolve, reject) => {
    const image = new Image();
    image.onload = () => resolve({ width: image.width, height: image.height });
    image.onerror = () => reject(new Error("Failed to load image dimensions."));
    image.src = dataUrl;
  });

const getImageData = async (file: File): Promise<ImageData> => {
  const dataUrl = await fileToDataUrl(file);
  const dimensions = await getImageDimensions(dataUrl);
  const format = file.type.includes("png") ? "PNG" : "JPEG";
  return { dataUrl, ...dimensions, format };
};

const drawHeader = (doc: jsPDF, title: string) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const generatedDate = new Date().toLocaleString();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Daily Development Report", PAGE_MARGIN, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`Report Title: ${title || "Untitled Daily Report"}`, PAGE_MARGIN, 26);
  doc.text(`Date Generated: ${generatedDate}`, PAGE_MARGIN, 32);

  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.4);
  doc.line(PAGE_MARGIN, 36, pageWidth - PAGE_MARGIN, 36);
};

const drawTableHeader = (
  doc: jsPDF,
  y: number,
  imageColumnWidth: number,
  featureColumnWidth: number,
  descriptionColumnWidth: number,
) => {
  const tableWidth = imageColumnWidth + featureColumnWidth + descriptionColumnWidth;

  doc.setFillColor(248, 250, 252);
  doc.rect(PAGE_MARGIN, y, tableWidth, 10, "F");
  doc.rect(PAGE_MARGIN, y, imageColumnWidth, 10);
  doc.rect(PAGE_MARGIN + imageColumnWidth, y, featureColumnWidth, 10);
  doc.rect(PAGE_MARGIN + imageColumnWidth + featureColumnWidth, y, descriptionColumnWidth, 10);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Image", PAGE_MARGIN + CELL_PADDING, y + 6.5);
  doc.text("Feature/Page", PAGE_MARGIN + imageColumnWidth + CELL_PADDING, y + 6.5);
  doc.text(
    "Description",
    PAGE_MARGIN + imageColumnWidth + featureColumnWidth + CELL_PADDING,
    y + 6.5,
  );
};

const addFooterToAllPages = (doc: jsPDF) => {
  const totalPages = doc.getNumberOfPages();
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();

  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text("Generated by Progress Hub", pageWidth / 2, pageHeight - FOOTER_Y_PADDING, {
      align: "center",
    });
    doc.setTextColor(0);
  }
};

export const exportReportToPdf = async (title: string, items: ReportItemData[]) => {
  const doc = new jsPDF({ orientation: "p", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const tableWidth = pageWidth - PAGE_MARGIN * 2;
  const imageColumnWidth = tableWidth * IMAGE_COLUMN_RATIO;
  const featureColumnWidth = tableWidth * FEATURE_COLUMN_RATIO;
  const descriptionColumnWidth = tableWidth - imageColumnWidth - featureColumnWidth;

  drawHeader(doc, title);
  let currentY = 42;
  drawTableHeader(doc, currentY, imageColumnWidth, featureColumnWidth, descriptionColumnWidth);
  currentY += 10;

  for (const item of items) {
    const featureText = item.featurePage.trim() || "No feature/page";
    const featureLines = doc.splitTextToSize(featureText, featureColumnWidth - CELL_PADDING * 2);
    const featureHeight = featureLines.length * 5 + CELL_PADDING * 2;

    const descriptionText = item.description.trim() || "No description";
    const descriptionLines = doc.splitTextToSize(
      descriptionText,
      descriptionColumnWidth - CELL_PADDING * 2,
    );
    const descriptionHeight = descriptionLines.length * 5 + CELL_PADDING * 2;

    let imageData: ImageData | null = null;
    if (item.image) {
      imageData = await getImageData(item.image);
    }

    const imageContentWidth = imageColumnWidth - CELL_PADDING * 2;
    const imageBoxHeight = imageData
      ? (imageContentWidth * imageData.height) / imageData.width
      : 0;
    const rowHeight = Math.max(
      ROW_MIN_HEIGHT,
      featureHeight,
      descriptionHeight,
      imageBoxHeight + CELL_PADDING * 2,
    );

    if (currentY + rowHeight > pageHeight - PAGE_MARGIN - 14) {
      doc.addPage();
      drawHeader(doc, title);
      currentY = 42;
      drawTableHeader(doc, currentY, imageColumnWidth, featureColumnWidth, descriptionColumnWidth);
      currentY += 10;
    }

    doc.rect(PAGE_MARGIN, currentY, imageColumnWidth, rowHeight);
    doc.rect(PAGE_MARGIN + imageColumnWidth, currentY, featureColumnWidth, rowHeight);
    doc.rect(
      PAGE_MARGIN + imageColumnWidth + featureColumnWidth,
      currentY,
      descriptionColumnWidth,
      rowHeight,
    );

    if (imageData) {
      const maxImageWidth = imageColumnWidth - CELL_PADDING * 2;
      const maxImageHeight = rowHeight - CELL_PADDING * 2;
      const imageRatio = imageData.width / imageData.height;
      const boxRatio = maxImageWidth / maxImageHeight;

      const renderWidth = imageRatio > boxRatio ? maxImageWidth : maxImageHeight * imageRatio;
      const renderHeight = imageRatio > boxRatio ? maxImageWidth / imageRatio : maxImageHeight;
      const imageX = PAGE_MARGIN + CELL_PADDING + (maxImageWidth - renderWidth) / 2;
      const imageY = currentY + CELL_PADDING + (maxImageHeight - renderHeight) / 2;

      doc.addImage(imageData.dataUrl, imageData.format, imageX, imageY, renderWidth, renderHeight);
    } else {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(10);
      doc.setTextColor(120);
      doc.text("No image", PAGE_MARGIN + CELL_PADDING, currentY + 8);
      doc.setTextColor(0);
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(featureLines, PAGE_MARGIN + imageColumnWidth + CELL_PADDING, currentY + 6.5, {
      maxWidth: featureColumnWidth - CELL_PADDING * 2,
    });
    doc.text(
      descriptionLines,
      PAGE_MARGIN + imageColumnWidth + featureColumnWidth + CELL_PADDING,
      currentY + 6.5,
      { maxWidth: descriptionColumnWidth - CELL_PADDING * 2 },
    );

    currentY += rowHeight;
  }

  addFooterToAllPages(doc);
  doc.save(`${(title || "daily-report").replace(/\s+/g, "-").toLowerCase()}.pdf`);
};
